import { CssSelectorNode, JssBlockItemNode, JssBlockNode, JssNode, JssSelectorNode, NodeType, SyntaxTree } from 'parser/syntaxTree';

const EXPORT_VAR_NAME = '_styles';
const SUB_BLOCKS_VAR_NAME = '_subBlocks';

function quoteEscape(str : string) : string {
    return str.replace('"', '\"');
}

function cssSelectors2js(selectors : JssSelectorNode[] | CssSelectorNode[]) : string {
    return '`' + selectors.map((item) => item.items.join('')).join(',') + '`';
}

function declarations2js(blockList : JssBlockItemNode[]) : string {
    return blockList
        .map((item) => {
            switch(item.type) {
                case NodeType.CssDeclaration:
                    return `value["${quoteEscape(item.prop)}"] = "${quoteEscape(item.value) + item.prio ? " " + item.prio : ""}";\n`;
                case NodeType.JssDeclaration:
                    //NOTE we do not parse content of the blocks here so an syntax error in the block can break the final code
                    return `value["${quoteEscape(item.prop)}"] = \`${item.value}\`;\n`;
                case NodeType.Ignore:
                    return '';
                case NodeType.JssBlock:
                    return jssBlock2js(item, SUB_BLOCKS_VAR_NAME);
                case NodeType.JssSpread:
                    return `Object.assign(value, ${item.value});`;
                default:
                    throw new Error(`unsupported block item ${JSON.stringify(item)}`);
            }
        })
        .join('');
}

function jssBlock2js(node : JssBlockNode, externalVarName : string = EXPORT_VAR_NAME) : string {
    return `(function(${EXPORT_VAR_NAME}) {
var ${SUB_BLOCKS_VAR_NAME} = [];
var name = ${cssSelectors2js(node.selectors)};
var value = {};
var self = { name: name, value: value };
${declarations2js(node.items)}
${EXPORT_VAR_NAME}.push(self);
for(var item of ${SUB_BLOCKS_VAR_NAME}) {
${EXPORT_VAR_NAME}.push(item);
}
}).bind(self)(${externalVarName});`;
}

function translateNode(node : JssNode) : string {
    switch(node.type) {
        case NodeType.Ignore:
            return node.items.map(item => item.trim()).join('') + "\n";
        case NodeType.Raw:
            return node.value;
        case NodeType.JssBlock:
            return jssBlock2js(node);
        case NodeType.CssSelector:
            return node.items.join(',');
        case NodeType.CssImport:
            return `${EXPORT_VAR_NAME}.push("@import ${quoteEscape(node.path)};");\n`;
        case NodeType.Comment:
        default:
            throw new Error(`unsupported node ${JSON.stringify(node)}`);
    }
}

export function translator(tree : SyntaxTree) : string {
    const result = tree.map(translateNode);

    return `// this code is autogenerated, do not edit it
var ${EXPORT_VAR_NAME} = [];
var self = null;
${result.join('')}

export ${EXPORT_VAR_NAME};`;
}
